// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login-service.proto

package login_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserEmail            string   `protobuf:"bytes,3,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	Level                string   `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Parent               int32    `protobuf:"varint,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	MemberId             int64    `protobuf:"varint,7,opt,name=memberId,proto3" json:"memberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e72aeb3ecf4818ca, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *User) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *User) GetParent() int32 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

type LoginRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e72aeb3ecf4818ca, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e72aeb3ecf4818ca, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
}

func init() { proto.RegisterFile("login-service.proto", fileDescriptor_e72aeb3ecf4818ca) }

var fileDescriptor_e72aeb3ecf4818ca = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x49, 0xda, 0xf4, 0x63, 0xfe, 0xff, 0x16, 0x99, 0x8a, 0x4c, 0x4b, 0x17, 0x25, 0xab,
	0x22, 0x98, 0x60, 0xdd, 0xb9, 0x73, 0xe1, 0x42, 0x10, 0xc1, 0x11, 0xc1, 0xed, 0xd4, 0x5c, 0xc2,
	0x60, 0x32, 0x13, 0xe7, 0x4e, 0xeb, 0xbe, 0xaf, 0xe0, 0x9b, 0xf8, 0x2a, 0xbe, 0x82, 0x0f, 0x22,
	0x33, 0x49, 0xea, 0x07, 0xee, 0xe6, 0x77, 0x2e, 0x9c, 0x9c, 0x73, 0x6f, 0xc8, 0xa4, 0xd0, 0xb9,
	0x54, 0x27, 0x08, 0x66, 0x2b, 0x1f, 0x21, 0xa9, 0x8c, 0xb6, 0x7a, 0x36, 0xcf, 0xb5, 0xce, 0x0b,
	0x48, 0x45, 0x25, 0x53, 0xa1, 0x94, 0xb6, 0xc2, 0x4a, 0xad, 0xb0, 0x9e, 0xc6, 0x6f, 0x01, 0xe9,
	0xde, 0x23, 0x18, 0x3a, 0x26, 0xa1, 0xcc, 0x58, 0xb0, 0x08, 0x96, 0x1d, 0x1e, 0xca, 0x8c, 0xce,
	0xc8, 0x60, 0x83, 0x60, 0x6e, 0x44, 0x09, 0x2c, 0x5c, 0x04, 0xcb, 0x21, 0xdf, 0x33, 0x9d, 0x93,
	0xa1, 0x7b, 0x5f, 0x96, 0x42, 0x16, 0xac, 0xe3, 0x87, 0x5f, 0x02, 0x3d, 0x24, 0x51, 0x01, 0x5b,
	0x28, 0x58, 0xd7, 0x4f, 0x6a, 0xa0, 0x47, 0xa4, 0x57, 0x09, 0x03, 0xca, 0xb2, 0x68, 0x11, 0x2c,
	0x23, 0xde, 0x90, 0xd3, 0xd1, 0x0a, 0xbb, 0x41, 0xd6, 0xab, 0xf5, 0x9a, 0xdc, 0xf7, 0x4b, 0x28,
	0xd7, 0x60, 0xae, 0x32, 0xd6, 0xf7, 0xa9, 0xf6, 0x1c, 0x3f, 0x90, 0xff, 0xd7, 0xae, 0x29, 0x87,
	0xe7, 0x0d, 0xa0, 0xa5, 0x07, 0xa4, 0x23, 0x2a, 0xe9, 0xc3, 0x0f, 0xb9, 0x7b, 0xb6, 0xe9, 0xd5,
	0xaf, 0xf4, 0x8e, 0xdd, 0xac, 0x12, 0x88, 0x2f, 0xda, 0x64, 0x4d, 0xf8, 0x3d, 0xc7, 0xbb, 0x80,
	0x8c, 0x1a, 0x6b, 0xac, 0xb4, 0x42, 0xf8, 0xc3, 0x9b, 0x91, 0x7e, 0x09, 0x88, 0x22, 0x6f, 0xad,
	0x5b, 0x74, 0xcd, 0xc1, 0x18, 0x6d, 0xbc, 0xed, 0x80, 0xd7, 0xe0, 0x54, 0xab, 0x9f, 0x40, 0xb5,
	0xfb, 0xf0, 0x40, 0xa7, 0xa4, 0xeb, 0x12, 0xf9, 0x6d, 0xfc, 0x5b, 0x45, 0x89, 0x3b, 0x02, 0xf7,
	0xd2, 0xea, 0xb6, 0xa9, 0x77, 0x57, 0xdf, 0x91, 0x5e, 0x90, 0xc8, 0x33, 0x1d, 0x25, 0xdf, 0x6b,
	0xcf, 0xc6, 0xc9, 0x8f, 0xa8, 0xf1, 0x74, 0xf7, 0xfe, 0xf1, 0x1a, 0x4e, 0xe2, 0x71, 0xba, 0x3d,
	0x4d, 0x9d, 0x53, 0xea, 0xff, 0x87, 0xf3, 0xe0, 0x78, 0xdd, 0xf3, 0xd7, 0x3e, 0xfb, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x90, 0xac, 0x35, 0x22, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type loginServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoginServiceClient(cc *grpc.ClientConn) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/LoginService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
type LoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedLoginServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoginServiceServer struct {
}

func (*UnimplementedLoginServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterLoginServiceServer(s *grpc.Server, srv LoginServiceServer) {
	s.RegisterService(&_LoginService_serviceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LoginService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login-service.proto",
}
